# Generated by Django 3.0.2 on 2021-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211115_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='out_of_stock',
            field=models.IntegerField(default=False, verbose_name='Нет в наличие'),
        ),
    ]
