# Generated by Django 3.0.2 on 2021-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Нет в наличие'),
        ),
    ]
